name: ci/cd

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ env.HEROKU_API_KEY }}
        heroku_app_name: api-themovieorg
        heroku_email: ${{ env.HEROKU_EMAIL }}
        usedocker: true